### ISSUE TITLE
Slow connection times

### ISSUE THREAD

**Issue by orai-arturo** [pions/webrtc#460] opened 2019-03-01 15:10 UTC
We are using pion/webrtc to set up communications between mobile apps and a backend server.

We are seeing connection times in the range of 5-6 seconds from the time the offer/answer exchange happens to the time the server receives a datachannel opened by the client.

Do you have suggestions for how we can get that to 1 second (or less, ideally).

**Comment by maxhawkins** [comment] 2019-03-02 02:18
Are you using trickle ICE to send the candidates as they're generated rather than all at once?

Depending on how you exchange the ICE candidates it could take a few seconds to generate a list of candidates client-side.

**Comment by orai-arturo** [comment] 2019-03-02 03:23
We do send the ice candidates in a bunch to the server.  We can also send them as they are ready.  It's after they are sent that we see about a 3-4s gap before the ICE connection state changes to Connected.  Then a second or more for any OnDataChannel calls to be made.

One thing I noticed is that the pion codebase does not seem to have onIceCandidate on RTCPeerConnection.

**Comment by trivigy** [comment] 2019-03-02 21:14
Just want to add my comment to the mix that stuff really did slow down since the last major merge. So far from what I see the `NewPeerConnection` stalls for quiet a while. Here are the two time stamps I get before and after. This is definitely slow.
```go
fmt.Fprintf(os.Stderr, "%+v\n", time.Now().Format(time.StampNano)) // Mar  2 15:57:58.796619086
rtc, err := webrtc.NewPeerConnection(webrtc.Configuration{
	ICEServers: []webrtc.ICEServer{
		{
			URLs: []string{"stun:stun.l.google.com:19302"},
		},
	},
})
if err != nil {
	return nil, &fail.UnknownError{Err: err}
}
fmt.Fprintf(os.Stderr, "%+v\n", time.Now().Format(time.StampNano)) // Mar  2 15:58:03.884905701
```

**Comment by trivigy** [comment] 2019-03-02 21:29
To add to bit more to the conversation, I started investigating this issue a bit more closely and can so far report that the issue is definitely due to slow gathering.
```go
fmt.Fprintf(os.Stderr, "%+v\n", time.Now().Format(time.StampNano)) // Mar  2 16:24:07.875860023
err = pc.gather()

if err != nil {
	return nil, err
}
fmt.Fprintf(os.Stderr, "%+v\n", time.Now().Format(time.StampNano)) // Mar  2 16:24:12.970730362
```

@maxhawkins Generally speaking I would support your point any time of the day but I think in this case this is a little too slow. Assuming the ICE does some reflexive gathering, it should still take in the areas of 200ms MAX, no pun intended :smile:, not 4sec.

**Comment by maxhawkins** [comment] 2019-03-02 21:30
Looks like a bug! I'll mark it as todo and see if anyone wants to take it on.

**Comment by maxhawkins** [comment] 2019-03-02 21:33
By the way @orai-arturo, you can join [our Slack channel](https://gophers.slack.com/messages/pion) if you'd like to talk to the maintainers in real time. It's usually pretty lively in there and it's easy to find help.

**Comment by Sean-Der** [comment] 2019-03-03 07:10
Hey @orai-arturo 
Thank you so much for using Pion WebRTC :)

I think the root issue here is that we don't implement `trickle ice` so we block until STUN communication finishes or times out. Out of curiosity could you try disabling IPV6 by commenting out [this](https://github.com/pions/webrtc/blob/master/internal/ice/networktype.go#L21) and reviewing what STUN servers you are using?

I have one big issue to handle right now (unified plan) but after that I can start to make progress on this. This also effects @trivigy and @maxhawkins so they might be able to help, and we also love outside contributions if you are interested in helping @orai-arturo but no pressure :) 

Thanks for you patience, and would love to have you on Slack also! always happy to debug realtime

**Comment by orai-arturo** [comment] 2019-03-04 16:00
We are just using the google and stunserver.org STUN servers.

**Comment by Sean-Der** [comment] 2019-03-04 19:05
Hey @orai-arturo 

You can sign-up for it [here](https://invite.slack.golangbridge.org/)

I would try your application with only the Google STUN servers (just for debugging) our STUN implementation is blocking so that might be surfacing a broken/slow STUN server. The browser is async so a poorly behaving STUN server will not have any negative side effects.

We will work on improving that, but not in the short term unfortunately

**Comment by trivigy** [comment] 2019-03-13 01:31
@orai-arturo I am just putting this for reference for you. The fix to the bug is about to be merged. This is how I am making this issue go away with the new fix.

Notice the `SetNetworkTypes` which only contains UDP4. This tells the library to only collect ipv4 addresses and ignore the rest.

```golang
mediaEngine := webrtc.MediaEngine{}
mediaEngine.RegisterDefaultCodecs()

settingEngine := webrtc.SettingEngine{}
settingEngine.SetNetworkTypes([]webrtc.NetworkType{webrtc.NetworkTypeUDP4})

api := webrtc.NewAPI(
	webrtc.WithMediaEngine(mediaEngine),
	webrtc.WithSettingEngine(settingEngine),
)

rtc, err := api.NewPeerConnection(webrtc.Configuration{
	ICEServers: []webrtc.ICEServer{
		{
			URLs: []string{"stun:stun.l.google.com:19302"},
		},
	},
})
```

**Closed** 2019-03-13 01:36 UTC
Labels: bug, help wanted, review
