### ISSUE TITLE
undefined reference to `dlopen'

### ISSUE THREAD

**Issue by reklatsmasters** [pions/webrtc#171] opened 2018-09-23 11:38 UTC
I'm trying to build datachannel example. I've got an error:

```
$ go get github.com/pions/webrtc/examples/data-channels

# github.com/pions/webrtc/internal/dtls
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x334): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3db): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x454): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x4fb): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x569): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5cb): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x603): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x69f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x709): undefined reference to `dlerror'
/usr/local/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x762): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
```

OS: Ubuntu 16.04.5 LTS

**Comment by backkem** [comment] 2018-09-23 13:29
Hi, I'm sadly not able to reproduce this. I'm also not entirely sure what could be causing it. Did you install the OpenSSL headers?

Overly elaborate guide to my testing, starting from a fresh `ubuntu-16.04.5-desktop-amd64` vm (may be helpful to some):
1. Install go:
```sh
wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.11.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
mkdir go
export GOPATH=/home/backkem/go
export PATH=$PATH:/home/backkem/go/bin
```
2. Install Git:
```sh
sudo apt-get update
sudo apt-get install git-core
```
3. Install OpenSSL headers:
```sh
sudo apt-get install libssl-dev
```
4. Host the examples (port 8080 to avoid privilege issues):
```sh
go get github.com/pions/webrtc/examples
cd go/src/github.com/pions/webrtc/examples/
examples --address=:8080
```
5. Run the ``data-channels`` example (redo the above ``export`` commands if you open a new terminal):
```sh
go get github.com/pions/webrtc/examples/data-channels
data-channels
```
6. Browse to [localhost:8080](http://localhost:8080).
7. Navigate to the data-channels example page.
8. Follow the example documentation to exchange the SDP offer/answer by copy/pasting.

**Comment by reklatsmasters** [comment] 2018-09-24 08:55
I found a similar problem https://stackoverflow.com/questions/40046145/go-run-throes-error-undefined-reference-to-dlopen?rq=1

However, i don't known how to add LDFLAGS with `-ldl` to `go get`.

**Comment by backkem** [comment] 2018-09-24 15:54
I have little experience with cgo so I'm not sure what this change does. Maybe @Sean-Der can comment on that. However, if you want to test this solution:
The answer on the page you linked seems to suggest adding `-ldl` to this line:
https://github.com/pions/webrtc/blob/9ed7683718f54edccdd2cf451f06f5f05243798f/internal/dtls/dtls.go#L7
The file is in `$gopath/src/github.com/pions/webrtc/internal/dtls/dtls.go`
After making the change you can 'install' the example as follows:
```sh
go install github.com/pions/webrtc/examples/data-channels
```
This will put the binary in ``$gopath/bin``. Assuming this path is part of your ``$path``, you can run the example as follows:
```sh
data-channels
```

**Comment by Sean-Der** [comment] 2018-09-24 17:57
Hey @reklatsmasters 

@backkem is 100% right about adding `-ldl`, hopefully that fixes your issue. 

What version of Go are you using? Is this a minimal install, in Docker? Just trying to reproduce myself. I use `16.04` + latest Go and haven't had this issue yet unfortunately.

**Comment by reklatsmasters** [comment] 2018-09-27 22:18
Oh, god. I solved my problem. I explicitly added `-ldl` after `libcrypto`. My changes:

```
// #cgo linux windows pkg-config: libssl libcrypto
#cgo linux CFLAGS: -I/usr/local/include -Wno-deprecated-declarations
#cgo linux LDFLAGS: -L/usr/local/lib -lssl -lcrypto -ldl
```

* go version go1.11 linux/amd64
* Ubuntu 16.04.5 LTS
* libssl-dev: 1.0.2g-1ubuntu4.13

**Comment by Sean-Der** [comment] 2018-09-28 06:40
Thank you so much for fixing that :) will open a PR and get that fixed!

If you are interested I would love to work together on getting `nodertc` and `pions` be perfectly compatible (if a user wants a nodejs implementation we should point to your repo, and vice versa). I would love to see WebRTC implementations that are native to each language!

We are decently active in Slack, so always happy to chat in there! Also feel free to grab any code (don't worry about attribution) ask any questions etc.. 

I will have to bother you about DTLS also, that is the next thing we have to work on (and will have plenty of questions!)

**Comment by Sean-Der** [comment] 2018-09-28 06:47
@reklatsmasters 
What does `pkg-config --cflags --libs libssl libcrypto` return? Does this patch help?
```
diff --git a/internal/dtls/dtls.go b/internal/dtls/dtls.go
index 11c3171..90dda19 100644
--- a/internal/dtls/dtls.go
+++ b/internal/dtls/dtls.go
@@ -3,6 +3,7 @@ package dtls
 /*
 #cgo linux windows pkg-config: libssl libcrypto
 #cgo linux CFLAGS: -Wno-deprecated-declarations
+#cgo linux LDFLAGS: -ldl
 #cgo darwin CFLAGS: -I/usr/local/opt/openssl/include -I/usr/local/opt/openssl/include -Wno-deprecated-declarations
 #cgo darwin LDFLAGS: -L/usr/local/opt/openssl/lib -L/usr/local/opt/openssl/lib -lssl -lcrypto
 #cgo windows CFLAGS: -DWIN32_LEAN_AND_MEAN
```

I am not sure, but could it be a mixup between your global install, and an install in `/usr/local`? We have to keep the `pkg-config` since most users will have different install paths unfortunately.

**Comment by reklatsmasters** [comment] 2018-09-30 20:55
@Sean-Der it should be

```
+ #cgo linux LDFLAGS: -lssl -lcrypto -ldl
```

Just `#cgo linux LDFLAGS: -ldl` doesn't work.

**Comment by joeky888** [comment] 2018-10-02 02:12
What are the outputs of `locate libdl.so` and `locate libdl.a`

For me it dumps

```sh
$ locate libdl.so
/usr/lib/libdl.so
/usr/lib/libdl.so.2
/usr/lib32/libdl.so
/usr/lib32/libdl.so.2

$ locate libdl.a
/usr/lib/libdl.a
/usr/lib32/libdl.a
```

If `locate libdl.a` is empty, I guess you need to install `libc6-dev`

**Comment by reklatsmasters** [comment] 2018-10-02 05:33
@joeky888

```
$ locate libdl.so
/lib/x86_64-linux-gnu/libdl.so.2
/lib32/libdl.so.2
/snap/coolreader3/1/lib/x86_64-linux-gnu/libdl.so.2
/snap/core/4917/lib/i386-linux-gnu/libdl.so.2
/snap/core/4917/lib/x86_64-linux-gnu/libdl.so.2
/snap/core/5145/lib/i386-linux-gnu/libdl.so.2
/snap/core/5145/lib/x86_64-linux-gnu/libdl.so.2
/snap/core/5328/lib/i386-linux-gnu/libdl.so.2
/snap/core/5328/lib/x86_64-linux-gnu/libdl.so.2
/usr/lib/x86_64-linux-gnu/libdl.so

$ locate libdl.a
/usr/lib/x86_64-linux-gnu/libdl.a
```

**Comment by Sean-Der** [comment] 2018-11-20 09:10
We just finished a Golang native version of DTLS 1.2 https://github.com/pions/dtls we won't be fixing any existing bugs with the OpenSSL version.

**Closed by Sean-Der** 2018-11-20 09:10 UTC
Labels: triaged
